Document: liblqr
Title: Debian liblqr Manual
Author: <insert document author here>
Abstract: This manual describes what liblqr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/liblqr/liblqr.sgml.gz

Format: postscript
Files: /usr/share/doc/liblqr/liblqr.ps.gz

Format: text
Files: /usr/share/doc/liblqr/liblqr.text.gz

Format: HTML
Index: /usr/share/doc/liblqr/html/index.html
Files: /usr/share/doc/liblqr/html/*.html

  
